### ISSUE TITLE
Improve scarplet examples; add missing data files

### ISSUE THREAD

**Issue by mcflugen** [rmsare/scarplet#60]
This issue is in regards to my JOSS review at openjournals/joss-reviews/issues/1066.

In running through the scarplet examples ([here](https://scarplet.readthedocs.io/en/latest) and [here](https://github.com/rmsare/scarplet/blob/master/README.md)) I have a couple suggestions.

1. [x] From the instructions, it's not clear that the examples need to be run from inside the `scarplet/tests` folder.
2. [x] Not all of the data files are available in the repository (e.g. `data/grandcanyon.tif` from the [Extracting Channels example](https://scarplet.readthedocs.io/en/latest/examples/channels.html))
3. [x] Provide the examples as notebooks users can download and run
4. [x] It would be nice if users could run the examples without having to grab the source code

In regards to the last point, I can think of two solutions
1. simply indicate at the start of each example where to get the data files (a URL to files within the *scarplet* repository would be fine)
2. include the data files with the package and have some way for users to load example data from within the installed package

**Comment by fclubb** [comment]
I agree with this: it wasn't immediately clear to me that the example data was included within the GitHub repository, as I had just done a `pip` install. It would be great to include a clearer statement of how users can get the example data (either state that they have to clone the GitHub repo, or provide the example data in a different way).

**Comment by rmsare** [comment]
Ah, this is unclear, I agree. I've updated the Readme and notebooks headers and made clear that examples and data live in the `docs/source/examples/` directory over in #66

**Comment by rmsare** [comment]
It's still not great to download stuff from the repo. I'm adding a `datasets` submodule so users can load sample data included with the package a la `sklearn.datasets.load_iris`.

**Comment by rmsare** [comment]
Okay, the examples have been refactored and documented with more clarity.

I am going to close this and re-open if either reviewer does not have success with installation and testing using conda.
