### ISSUE TITLE
Issue with running examples on Ubuntu 18.04 - conflicting dependencies

### ISSUE THREAD

**Issue by fclubb** [rmsare/scarplet#62]
I had an error when trying to run the example script on Ubuntu 18.04 after installing `scarplet` via `pip`:

```
import numpy as np
import scarplet as sl
from scarplet.WindowedTemplate import Scarp

params = {'scale': 100,
          'age': 10,
          'ang_min': -10 * np.pi / 2,
          'ang_max': 10 * np.pi / 2
         }

data = sl.load('data/faultzone.tif')
res = sl.match(data, Scarp, **params)

sl.plot_results(data, res)
```
The error was the following:
```
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
```
**Desktop:**
 - OS: Ubuntu 18.04
 - Python Version 3.6 (Miniconda install)

I haven't managed to fix the problem despite trying the solutions suggested on this StackOverflow page: https://stackoverflow.com/questions/50555973/qgtkstyle-could-not-resolve-gtk 

I tried to update qt using conda: 
```
conda install qt=5.9
```
Then I got some issues with other libraries which I think is a gdal issue. I already had gdal 2.2.4 installed via conda-forge.
```
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```
I think a potential solution is to make sure all the dependencies are properly accounted for during the pip install, or implement the conda package install. Alternatively provide an environment file so that the install of a specific version of gdal doesn't mess up the users' existing python install.

**Comment by rmsare** [comment]
Thanks for this @fclubb. I have run into object file problems with GDAL before, and I've packaged via conda per your and @mcflugen's suggestions. Once it's through the conda-forge process I can ping you and we can see if this issue is resolved.

**Comment by rmsare** [comment]
It looks like the conda recipe will be a while in review after all.

Is this error resolved when installing the dependencies through conda with changes in #64?

```
git clone https://github.com/rmsare/scarplet
cd scarplet
conda install --file=requirements.txt -c conda-forge
python setup.py develop
```

**Comment by rmsare** [comment]
@fclubb The package is now up on conda-forge and example data is provided in v0.1.3. When you have a moment would you mind checking to see if this is resolved?

Thanks for your help and patience with this.
