### ISSUE TITLE
ImportError from dask.array.fft.fftfreq

### ISSUE THREAD

**Issue by rmsare** [rmsare/scarplet#71]
**Describe the bug**
pyFFTW throws an ImportError when dask_fft is imported.

**To Reproduce**
1. Install scarplet
2. Activate environment
3. Import scarplet module

**Desktop (please complete the following information):**
 - Windows and Python version is 3.4.3 and 2.7.12.

**Additional context**
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-bc5e50ca174b> in <module>()
----> 1 import scarplet as sl
      2 from scarplet.datasets import load_carrizo
      3 from scarplet.WindowedTemplate import Scarp

C:\Users\Ara\Anaconda3\lib\site-packages\scarplet\__init__.py in <module>()
----> 1 from scarplet.core import *

C:\Users\Ara\Anaconda3\lib\site-packages\scarplet\core.py in <module>()
     10 import matplotlib.pyplot as plt
     11 
---> 12 import pyfftw
     13 from pyfftw.interfaces.numpy_fft import fft2, ifft2, fftshift
     14 

C:\Users\Ara\Anaconda3\lib\site-packages\pyfftw\__init__.py in <module>()
     41 from . import config
     42 from . import builders
---> 43 from . import interfaces
     44 
     45 

C:\Users\Ara\Anaconda3\lib\site-packages\pyfftw\interfaces\__init__.py in <module>()
    245 
    246 if fft_wrap:
--> 247     from . import dask_fft
    248 del fft_wrap

C:\Users\Ara\Anaconda3\lib\site-packages\pyfftw\interfaces\dask_fft.py in <module>()
     55 
     56 from . import numpy_fft as _numpy_fft
---> 57 from dask.array.fft import (
     58     fft_wrap,
     59     fftfreq,

ImportError: cannot import name 'fftfreq'
```

**Comment by rmsare** [comment]
I can't reproduce this in a fresh environment on Ubuntu Linux. It looks like an issue with the OSX package for pyfftw.

**Comment by AraJeong** [comment]
Hi Rob,
My operating system is Windows and Python version is 3.4.3 and 2.7.12.
- Ara

**Comment by rmsare** [comment]
@AraJeong Thanks - that explains it. This package is only available for OS X or Linux. 

Can you install it on another machine?

**Comment by AraJeong** [comment]
@rmsare Oh... That was the reason. Okay. I will install it on iMac and let you know whether it works or not. Thank you.

**Comment by rmsare** [comment]
Great, thanks for trying it on a Mac. Yeah, Windows isn't supported for this reason - there are pyfftw compatibility issues.

Let me know how it goes.
